[project]
name = "diy-mono"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = ["diydev", "diyui"]

[tool.uv]
package = false

[tool.uv.workspace]
members = ["packages/diyui.py", "packages/diydev"]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"

[tool.uv.sources]
diyui = { workspace = true }
diydev = { workspace = true }

