from __future__ import annotations

from typing import Any

import panel as pn

from .._base import UIComponent


class DataFrame(UIComponent, pn.pane.DataFrame):

    def __init__(
        self,
        object: Any | None = None,
        *,
        name: str = "",
        align: Any = "start",
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = (5, 10),
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = "auto",
        height_policy: Any = "auto",
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        default_layout: Any = pn.Row,
        enable_streaming: bool = False,
        disable_math: bool = True,
        sanitize_html: bool = False,
        bold_rows: bool = True,
        border: int = 0,
        classes: list[str] | None = None,
        col_space: str | int | dict[str, Any] | None = None,
        decimal: str = ".",
        escape: bool = True,
        float_format: str | None = None,
        formatters: dict[str, Any] | list[Any] | None = None,
        header: bool = True,
        index: bool = True,
        index_names: bool = True,
        justify: Any | None = None,
        max_rows: int | None = None,
        max_cols: int | None = None,
        na_rep: str = "NaN",
        render_links: bool = False,
        show_dimensions: bool = False,
        sparsify: bool = True,
        text_align: Any = "start",
    ) -> None:
        UIComponent.__init__(self)
        pn.pane.DataFrame.__init__(
            self,
            object,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes or [],
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles or {},
            stylesheets=stylesheets or [],
            tags=tags or [],
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            default_layout=default_layout,
            enable_streaming=enable_streaming,
            disable_math=disable_math,
            sanitize_html=sanitize_html,
            bold_rows=bold_rows,
            border=border,
            classes=classes or ["panel-df"],
            col_space=col_space,
            decimal=decimal,
            escape=escape,
            float_format=float_format,
            formatters=formatters,
            header=header,
            index=index,
            index_names=index_names,
            justify=justify,
            max_rows=max_rows,
            max_cols=max_cols,
            na_rep=na_rep,
            render_links=render_links,
            show_dimensions=show_dimensions,
            sparsify=sparsify,
            text_align=text_align,
        )
