"""app.layout.xxx() 工厂类 — 由 tools/_generate_factories.py 自动生成，勿手改。"""

from __future__ import annotations
from typing import Any

from .. import layout as _layout
from ._layout_factory import _LayoutFactoryBase


class _LayoutFactory(_LayoutFactoryBase):
    """app.layout.xxx() 工厂方法（自动生成）。"""

    def accordion(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = [],
        active: 'list[Any]' = [],
        scroll: "False | True | 'both-auto' | 'y-auto' | 'x-auto' | both | x | y" = False,
        active_header_background: 'str | None' = None,
        header_color: str = '',
        header_background: str = '',
        toggle: bool = False,
        **kwargs: Any,
    ) -> _layout.Accordion:
        return self._add(_layout.Accordion(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            active=active,
            scroll=scroll,
            active_header_background=active_header_background,
            header_color=header_color,
            header_background=header_background,
            toggle=toggle,
            **kwargs,
        ))

    def card(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = ['card'],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = [],
        scroll: "False | True | 'both-auto' | 'y-auto' | 'x-auto' | both | x | y" = False,
        auto_scroll_limit: int = 0,
        scroll_button_threshold: int = 0,
        scroll_position: int = 0,
        view_latest: bool = False,
        active_header_background: 'str | None' = None,
        button_css_classes: 'list[Any]' = ['card-button'],
        collapsible: bool = True,
        collapsed: bool = False,
        header: 'Any | None' = None,
        header_background: str = '',
        header_color: str = '',
        header_css_classes: 'list[Any]' = ['card-header'],
        hide_header: bool = False,
        title_css_classes: 'list[Any]' = ['card-title'],
        title: str = '',
        **kwargs: Any,
    ) -> _layout.Card:
        return self._add(_layout.Card(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            scroll=scroll,
            auto_scroll_limit=auto_scroll_limit,
            scroll_button_threshold=scroll_button_threshold,
            scroll_position=scroll_position,
            view_latest=view_latest,
            active_header_background=active_header_background,
            button_css_classes=button_css_classes,
            collapsible=collapsible,
            collapsed=collapsed,
            header=header,
            header_background=header_background,
            header_color=header_color,
            header_css_classes=header_css_classes,
            hide_header=hide_header,
            title_css_classes=title_css_classes,
            title=title,
            **kwargs,
        ))

    def column(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = [],
        scroll: "False | True | 'both-auto' | 'y-auto' | 'x-auto' | both | x | y" = False,
        auto_scroll_limit: int = 0,
        scroll_button_threshold: int = 0,
        scroll_position: int = 0,
        view_latest: bool = False,
        **kwargs: Any,
    ) -> _layout.Column:
        return self._add(_layout.Column(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            scroll=scroll,
            auto_scroll_limit=auto_scroll_limit,
            scroll_button_threshold=scroll_button_threshold,
            scroll_position=scroll_position,
            view_latest=view_latest,
            **kwargs,
        ))

    def divider(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'fit',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        **kwargs: Any,
    ) -> _layout.Divider:
        return self._add(_layout.Divider(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            **kwargs,
        ))

    def feed(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = [],
        scroll: "False | True | 'both-auto' | 'y-auto' | 'x-auto' | both | x | y" = 'y',
        auto_scroll_limit: int = 0,
        scroll_button_threshold: int = 0,
        scroll_position: int = 0,
        view_latest: bool = False,
        load_buffer: int = 50,
        visible_range: 'Any | None' = None,
        **kwargs: Any,
    ) -> _layout.Feed:
        return self._add(_layout.Feed(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            scroll=scroll,
            auto_scroll_limit=auto_scroll_limit,
            scroll_button_threshold=scroll_button_threshold,
            scroll_position=scroll_position,
            view_latest=view_latest,
            load_buffer=load_buffer,
            visible_range=visible_range,
            **kwargs,
        ))

    def flex_box(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = [],
        align_content: "normal | 'flex-start' | 'flex-end' | center | 'space-between' | 'space-around' | 'space-evenly' | stretch | start | end | baseline | 'first baseline' | 'last baseline'" = 'flex-start',
        align_items: "stretch | 'flex-start' | 'flex-end' | center | baseline | 'first baseline' | 'last baseline' | start | end | 'self-start' | 'self-end'" = 'flex-start',
        flex_direction: "row | 'row-reverse' | column | 'column-reverse'" = 'row',
        flex_wrap: "nowrap | wrap | 'wrap-reverse'" = 'wrap',
        gap: str = '',
        justify_content: "'flex-start' | 'flex-end' | center | 'space-between' | 'space-around' | 'space-evenly' | start | end | left | right" = 'flex-start',
        **kwargs: Any,
    ) -> _layout.FlexBox:
        return self._add(_layout.FlexBox(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            align_content=align_content,
            align_items=align_items,
            flex_direction=flex_direction,
            flex_wrap=flex_wrap,
            gap=gap,
            justify_content=justify_content,
            **kwargs,
        ))

    def float_panel(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = [],
        config: 'dict[str, Any]' = {},
        contained: bool = True,
        position: "center | 'left-top' | 'center-top' | 'right-top' | 'right-center' | 'right-bottom' | 'center-bottom' | 'left-bottom' | 'left-center'" = 'right-top',
        offsetx: 'int | None' = None,
        offsety: 'int | None' = None,
        theme: str = 'primary',
        status: "normalized | maximized | minimized | smallified | smallifiedmax | closed" = 'normalized',
        **kwargs: Any,
    ) -> _layout.FloatPanel:
        return self._add(_layout.FloatPanel(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            config=config,
            contained=contained,
            position=position,
            offsetx=offsetx,
            offsety=offsety,
            theme=theme,
            status=status,
            **kwargs,
        ))

    def grid_box(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = [],
        scroll: "False | True | 'both-auto' | 'y-auto' | 'x-auto' | both | x | y" = False,
        nrows: 'int | None' = None,
        ncols: 'int | None' = None,
        **kwargs: Any,
    ) -> _layout.GridBox:
        return self._add(_layout.GridBox(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            scroll=scroll,
            nrows=nrows,
            ncols=ncols,
            **kwargs,
        ))

    def grid_spec(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = {},
        mode: "warn | error | override" = 'warn',
        ncols: 'int | None' = None,
        nrows: 'int | None' = None,
        **kwargs: Any,
    ) -> _layout.GridSpec:
        return self._add(_layout.GridSpec(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            mode=mode,
            ncols=ncols,
            nrows=nrows,
            **kwargs,
        ))

    def grid_stack(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = {},
        mode: "warn | error | override" = 'warn',
        ncols: 'int | None' = None,
        nrows: 'int | None' = None,
        allow_resize: bool = True,
        allow_drag: bool = True,
        state: 'list[Any]' = [],
        **kwargs: Any,
    ) -> _layout.GridStack:
        return self._add(_layout.GridStack(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            mode=mode,
            ncols=ncols,
            nrows=nrows,
            allow_resize=allow_resize,
            allow_drag=allow_drag,
            state=state,
            **kwargs,
        ))

    def h_spacer(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: Any = 'stretch_width',
        visible: bool = True,
        loading: bool = False,
        **kwargs: Any,
    ) -> _layout.HSpacer:
        return self._add(_layout.HSpacer(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            **kwargs,
        ))

    def modal(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = [],
        scroll: "False | True | 'both-auto' | 'y-auto' | 'x-auto' | both | x | y" = False,
        open: bool = False,
        show_close_button: bool = True,
        background_close: bool = True,
        **kwargs: Any,
    ) -> _layout.Modal:
        return self._add(_layout.Modal(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            scroll=scroll,
            open=open,
            show_close_button=show_close_button,
            background_close=background_close,
            **kwargs,
        ))

    def row(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = [],
        scroll: "False | True | 'both-auto' | 'y-auto' | 'x-auto' | both | x | y" = False,
        **kwargs: Any,
    ) -> _layout.Row:
        return self._add(_layout.Row(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            scroll=scroll,
            **kwargs,
        ))

    def spacer(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        **kwargs: Any,
    ) -> _layout.Spacer:
        return self._add(_layout.Spacer(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            **kwargs,
        ))

    def swipe(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = [],
        slider_width: int = 5,
        slider_color: str = 'black',
        start: int = 0,
        end: int = 100,
        value: int = 50,
        _before: 'Any | None' = None,
        _after: 'Any | None' = None,
        **kwargs: Any,
    ) -> _layout.Swipe:
        return self._add(_layout.Swipe(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            slider_width=slider_width,
            slider_color=slider_color,
            start=start,
            end=end,
            value=value,
            _before=_before,
            _after=_after,
            **kwargs,
        ))

    def tabs(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = [],
        active: int = 0,
        scroll: "False | True | 'both-auto' | 'y-auto' | 'x-auto' | both | x | y" = False,
        closable: bool = False,
        dynamic: bool = False,
        tabs_location: "above | below | left | right" = 'above',
        **kwargs: Any,
    ) -> _layout.Tabs:
        return self._add(_layout.Tabs(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            active=active,
            scroll=scroll,
            closable=closable,
            dynamic=dynamic,
            tabs_location=tabs_location,
            **kwargs,
        ))

    def v_spacer(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: Any = 'stretch_height',
        visible: bool = True,
        loading: bool = False,
        **kwargs: Any,
    ) -> _layout.VSpacer:
        return self._add(_layout.VSpacer(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            **kwargs,
        ))

    def widget_box(self,
        *children: Any,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = ['panel-widget-box'],
        design: Any = None,
        height: 'int | None' = None,
        min_width: 'int | None' = None,
        min_height: 'int | None' = None,
        max_width: 'int | None' = None,
        max_height: 'int | None' = None,
        margin: 'tuple[int, int] | int | str | None' = 0,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        visible: bool = True,
        loading: bool = False,
        objects: Any = [],
        scroll: "False | True | 'both-auto' | 'y-auto' | 'x-auto' | both | x | y" = False,
        disabled: bool = False,
        horizontal: bool = False,
        **kwargs: Any,
    ) -> _layout.WidgetBox:
        return self._add(_layout.WidgetBox(
            *children,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            scroll=scroll,
            disabled=disabled,
            horizontal=horizontal,
            **kwargs,
        ))

