"""app.layout.xxx() 工厂类 — 由 tools/_generate_factories.py 自动生成，勿手改。"""

from __future__ import annotations
from typing import Any

from .. import layout as _layout


class _LayoutFactoryGen:
    """app.layout.xxx() 工厂方法（自动生成）。"""

    def accordion(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        active: list[int] | None = None,
        scroll: Any = False,
        active_header_background: str | None = None,
        header_color: str = '',
        header_background: str = '',
        toggle: bool = False,
        **kwargs: Any,
    ) -> _layout.Accordion:
        return self._add(_layout.Accordion(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            active=active,
            scroll=scroll,
            active_header_background=active_header_background,
            header_color=header_color,
            header_background=header_background,
            toggle=toggle,
            **kwargs,
        ))

    def card(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        scroll: Any = False,
        auto_scroll_limit: int = 0,
        scroll_button_threshold: int = 0,
        scroll_position: int = 0,
        view_latest: bool = False,
        active_header_background: str | None = None,
        button_css_classes: list[Any] | None = None,
        collapsible: bool = True,
        collapsed: bool = False,
        header: Any | None = None,
        header_background: str = '',
        header_color: str = '',
        header_css_classes: list[Any] | None = None,
        hide_header: bool = False,
        title_css_classes: list[Any] | None = None,
        title: str = '',
        **kwargs: Any,
    ) -> _layout.Card:
        return self._add(_layout.Card(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            scroll=scroll,
            auto_scroll_limit=auto_scroll_limit,
            scroll_button_threshold=scroll_button_threshold,
            scroll_position=scroll_position,
            view_latest=view_latest,
            active_header_background=active_header_background,
            button_css_classes=button_css_classes,
            collapsible=collapsible,
            collapsed=collapsed,
            header=header,
            header_background=header_background,
            header_color=header_color,
            header_css_classes=header_css_classes,
            hide_header=hide_header,
            title_css_classes=title_css_classes,
            title=title,
            **kwargs,
        ))

    def column(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        scroll: Any = False,
        auto_scroll_limit: int = 0,
        scroll_button_threshold: int = 0,
        scroll_position: int = 0,
        view_latest: bool = False,
        **kwargs: Any,
    ) -> _layout.Column:
        return self._add(_layout.Column(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            scroll=scroll,
            auto_scroll_limit=auto_scroll_limit,
            scroll_button_threshold=scroll_button_threshold,
            scroll_position=scroll_position,
            view_latest=view_latest,
            **kwargs,
        ))

    def divider(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        **kwargs: Any,
    ) -> _layout.Divider:
        return self._add(_layout.Divider(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            **kwargs,
        ))

    def feed(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        scroll: Any = 'y',
        auto_scroll_limit: int = 0,
        scroll_button_threshold: int = 0,
        scroll_position: int = 0,
        view_latest: bool = False,
        load_buffer: int = 50,
        **kwargs: Any,
    ) -> _layout.Feed:
        return self._add(_layout.Feed(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            scroll=scroll,
            auto_scroll_limit=auto_scroll_limit,
            scroll_button_threshold=scroll_button_threshold,
            scroll_position=scroll_position,
            view_latest=view_latest,
            load_buffer=load_buffer,
            **kwargs,
        ))

    def flex_box(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        align_content: Any = 'flex-start',
        align_items: Any = 'flex-start',
        flex_direction: Any = 'row',
        flex_wrap: Any = 'wrap',
        gap: str = '',
        justify_content: Any = 'flex-start',
        **kwargs: Any,
    ) -> _layout.FlexBox:
        return self._add(_layout.FlexBox(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            align_content=align_content,
            align_items=align_items,
            flex_direction=flex_direction,
            flex_wrap=flex_wrap,
            gap=gap,
            justify_content=justify_content,
            **kwargs,
        ))

    def float_panel(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        config: dict[str, Any] | None = None,
        contained: bool = True,
        position: Any = 'right-top',
        offsetx: int | None = None,
        offsety: int | None = None,
        theme: str = 'primary',
        status: Any = 'normalized',
        **kwargs: Any,
    ) -> _layout.FloatPanel:
        return self._add(_layout.FloatPanel(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            config=config,
            contained=contained,
            position=position,
            offsetx=offsetx,
            offsety=offsety,
            theme=theme,
            status=status,
            **kwargs,
        ))

    def grid_box(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        scroll: Any = False,
        nrows: int | None = None,
        ncols: int | None = None,
        **kwargs: Any,
    ) -> _layout.GridBox:
        return self._add(_layout.GridBox(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            scroll=scroll,
            nrows=nrows,
            ncols=ncols,
            **kwargs,
        ))

    def grid_spec(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        objects: dict[str, Any] | None = None,
        mode: Any = 'warn',
        ncols: int | None = None,
        nrows: int | None = None,
        **kwargs: Any,
    ) -> _layout.GridSpec:
        return self._add(_layout.GridSpec(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            mode=mode,
            ncols=ncols,
            nrows=nrows,
            **kwargs,
        ))

    def grid_stack(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        objects: dict[str, Any] | None = None,
        mode: Any = 'warn',
        ncols: int | None = None,
        nrows: int | None = None,
        allow_resize: bool = True,
        allow_drag: bool = True,
        state: list[Any] | None = None,
        **kwargs: Any,
    ) -> _layout.GridStack:
        return self._add(_layout.GridStack(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            objects=objects,
            mode=mode,
            ncols=ncols,
            nrows=nrows,
            allow_resize=allow_resize,
            allow_drag=allow_drag,
            state=state,
            **kwargs,
        ))

    def h_spacer(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        visible: bool = True,
        loading: bool = False,
        **kwargs: Any,
    ) -> _layout.HSpacer:
        return self._add(_layout.HSpacer(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            visible=visible,
            loading=loading,
            **kwargs,
        ))

    def modal(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        scroll: Any = False,
        open: bool = False,
        show_close_button: bool = True,
        background_close: bool = True,
        **kwargs: Any,
    ) -> _layout.Modal:
        return self._add(_layout.Modal(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            scroll=scroll,
            open=open,
            show_close_button=show_close_button,
            background_close=background_close,
            **kwargs,
        ))

    def row(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        scroll: Any = False,
        **kwargs: Any,
    ) -> _layout.Row:
        return self._add(_layout.Row(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            scroll=scroll,
            **kwargs,
        ))

    def spacer(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        **kwargs: Any,
    ) -> _layout.Spacer:
        return self._add(_layout.Spacer(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            **kwargs,
        ))

    def swipe(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        slider_width: int = 5,
        slider_color: str = 'black',
        start: int = 0,
        end: int = 100,
        value: int = 50,
        **kwargs: Any,
    ) -> _layout.Swipe:
        return self._add(_layout.Swipe(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            slider_width=slider_width,
            slider_color=slider_color,
            start=start,
            end=end,
            value=value,
            **kwargs,
        ))

    def tabs(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        active: int = 0,
        scroll: Any = False,
        closable: bool = False,
        dynamic: bool = False,
        tabs_location: Any = 'above',
        **kwargs: Any,
    ) -> _layout.Tabs:
        return self._add(_layout.Tabs(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            active=active,
            scroll=scroll,
            closable=closable,
            dynamic=dynamic,
            tabs_location=tabs_location,
            **kwargs,
        ))

    def v_spacer(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        visible: bool = True,
        loading: bool = False,
        **kwargs: Any,
    ) -> _layout.VSpacer:
        return self._add(_layout.VSpacer(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            visible=visible,
            loading=loading,
            **kwargs,
        ))

    def widget_box(self,
        *children: Any,
        name: str = '',
        align: Any = 'start',
        aspect_ratio: Any | None = None,
        css_classes: list[Any] | None = None,
        design: Any = None,
        height: int | None = None,
        min_width: int | None = None,
        min_height: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        margin: Any | None = 0,
        styles: dict[str, Any] | None = None,
        stylesheets: list[Any] | None = None,
        tags: list[Any] | None = None,
        width: int | None = None,
        width_policy: Any = 'auto',
        height_policy: Any = 'auto',
        sizing_mode: Any = None,
        visible: bool = True,
        loading: bool = False,
        scroll: Any = False,
        disabled: bool = False,
        horizontal: bool = False,
        **kwargs: Any,
    ) -> _layout.WidgetBox:
        return self._add(_layout.WidgetBox(
            *children,
            name=name,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            design=design,
            height=height,
            min_width=min_width,
            min_height=min_height,
            max_width=max_width,
            max_height=max_height,
            margin=margin,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            width=width,
            width_policy=width_policy,
            height_policy=height_policy,
            sizing_mode=sizing_mode,
            visible=visible,
            loading=loading,
            scroll=scroll,
            disabled=disabled,
            horizontal=horizontal,
            **kwargs,
        ))

