"""app.pane.xxx() 工厂类 — 由 tools/_generate_factories.py 自动生成，勿手改。"""

from __future__ import annotations
from typing import Any

from .. import pane as _pane
from ._pane_factory import _PaneFactoryBase


class _PaneFactory(_PaneFactoryBase):
    """app.pane.xxx() 工厂方法（自动生成）。"""

    def avif(self,
        align: 'str | tuple[str, str]' = 'start',
        alt_text: 'str | None' = None,
        aspect_ratio: 'Any | None' = None,
        caption: 'str | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        embed: bool = False,
        enable_streaming: bool = False,
        fixed_aspect: bool = True,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        link_url: 'str | None' = None,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        target: str = '_blank',
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.AVIF:
        return self._add(_pane.AVIF(
            align=align,
            alt_text=alt_text,
            aspect_ratio=aspect_ratio,
            caption=caption,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            embed=embed,
            enable_streaming=enable_streaming,
            fixed_aspect=fixed_aspect,
            height=height,
            height_policy=height_policy,
            link_url=link_url,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            target=target,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def alert(self,
        alert_type: "primary | secondary | success | danger | warning | info | light | dark" = 'primary',
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        dedent: bool = True,
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        disable_anchors: bool = False,
        disable_math: bool = False,
        enable_streaming: bool = False,
        extensions: 'list[Any]' = ['extra', 'smarty', 'codehilite'],
        hard_line_break: bool = False,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        plugins: 'list[Any]' = [],
        renderer: "'markdown-it' | myst | markdown" = 'markdown-it',
        renderer_options: 'dict[str, Any]' = {},
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.Alert:
        return self._add(_pane.Alert(
            alert_type=alert_type,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            dedent=dedent,
            default_layout=default_layout,
            design=design,
            disable_anchors=disable_anchors,
            disable_math=disable_math,
            enable_streaming=enable_streaming,
            extensions=extensions,
            hard_line_break=hard_line_break,
            height=height,
            height_policy=height_policy,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            plugins=plugins,
            renderer=renderer,
            renderer_options=renderer_options,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def audio(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        autoplay: bool = False,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        loading: bool = False,
        loop: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        muted: bool = False,
        object: 'str | bytes | Path' = '',
        paused: bool = True,
        sample_rate: int = 44100,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        throttle: int = 250,
        time: float = 0,
        visible: bool = True,
        volume: 'float | None' = None,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.Audio:
        return self._add(_pane.Audio(
            align=align,
            aspect_ratio=aspect_ratio,
            autoplay=autoplay,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            height=height,
            height_policy=height_policy,
            loading=loading,
            loop=loop,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            muted=muted,
            object=object,
            paused=paused,
            sample_rate=sample_rate,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            throttle=throttle,
            time=time,
            visible=visible,
            volume=volume,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def bokeh(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        autodispatch: bool = True,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        theme: 'Theme | str' = None,
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.Bokeh:
        return self._add(_pane.Bokeh(
            align=align,
            aspect_ratio=aspect_ratio,
            autodispatch=autodispatch,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            height=height,
            height_policy=height_policy,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            theme=theme,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def data_frame(self,
        _object: 'Any | None' = None,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        bold_rows: bool = True,
        border: int = 0,
        classes: 'list[Any]' = ['panel-df'],
        col_space: 'str | int | dict' = None,
        css_classes: 'list[Any]' = [],
        decimal: str = '.',
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        disable_math: bool = True,
        enable_streaming: bool = False,
        escape: bool = True,
        float_format: 'collections.abc.Callable | None' = None,
        formatters: 'dict | list' = None,
        header: bool = True,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        index: bool = True,
        index_names: bool = True,
        justify: "left | right | center | justify | 'justify-all' | start | end | inherit | 'match-parent' | initial | unset" = None,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_cols: 'int | None' = None,
        max_height: 'int | None' = None,
        max_rows: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        na_rep: str = 'NaN',
        object: 'Any | None' = None,
        render_links: bool = False,
        sanitize_hook: 'collections.abc.Callable' = None,
        sanitize_html: bool = False,
        show_dimensions: bool = False,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        sparsify: bool = True,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        text_align: "start | end | center" = None,
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.DataFrame:
        return self._add(_pane.DataFrame(
            _object=_object,
            align=align,
            aspect_ratio=aspect_ratio,
            bold_rows=bold_rows,
            border=border,
            classes=classes,
            col_space=col_space,
            css_classes=css_classes,
            decimal=decimal,
            default_layout=default_layout,
            design=design,
            disable_math=disable_math,
            enable_streaming=enable_streaming,
            escape=escape,
            float_format=float_format,
            formatters=formatters,
            header=header,
            height=height,
            height_policy=height_policy,
            index=index,
            index_names=index_names,
            justify=justify,
            loading=loading,
            margin=margin,
            max_cols=max_cols,
            max_height=max_height,
            max_rows=max_rows,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            na_rep=na_rep,
            object=object,
            render_links=render_links,
            sanitize_hook=sanitize_hook,
            sanitize_html=sanitize_html,
            show_dimensions=show_dimensions,
            sizing_mode=sizing_mode,
            sparsify=sparsify,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            text_align=text_align,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def deck_gl(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        click_state: 'dict[str, Any]' = {},
        configuration: str = '',
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        hover_state: 'dict[str, Any]' = {},
        loading: bool = False,
        mapbox_api_key: 'str | None' = None,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        throttle: 'dict[str, Any]' = {'view': 200, 'hover': 200},
        tooltips: 'bool | dict' = True,
        view_state: 'dict[str, Any]' = {},
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.DeckGL:
        return self._add(_pane.DeckGL(
            align=align,
            aspect_ratio=aspect_ratio,
            click_state=click_state,
            configuration=configuration,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            height=height,
            height_policy=height_policy,
            hover_state=hover_state,
            loading=loading,
            mapbox_api_key=mapbox_api_key,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            throttle=throttle,
            tooltips=tooltips,
            view_state=view_state,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def e_charts(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        options: 'dict[str, Any] | None' = None,
        renderer: "canvas | svg" = 'canvas',
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        theme: "default | light | dark" = 'default',
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.ECharts:
        return self._add(_pane.ECharts(
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            height=height,
            height_policy=height_policy,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            options=options,
            renderer=renderer,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            theme=theme,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def gif(self,
        align: 'str | tuple[str, str]' = 'start',
        alt_text: 'str | None' = None,
        aspect_ratio: 'Any | None' = None,
        caption: 'str | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        embed: bool = False,
        enable_streaming: bool = False,
        fixed_aspect: bool = True,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        link_url: 'str | None' = None,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        target: str = '_blank',
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.GIF:
        return self._add(_pane.GIF(
            align=align,
            alt_text=alt_text,
            aspect_ratio=aspect_ratio,
            caption=caption,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            embed=embed,
            enable_streaming=enable_streaming,
            fixed_aspect=fixed_aspect,
            height=height,
            height_policy=height_policy,
            link_url=link_url,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            target=target,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def html(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        disable_math: bool = True,
        enable_streaming: bool = False,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sanitize_hook: 'collections.abc.Callable' = None,
        sanitize_html: bool = False,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.HTML:
        return self._add(_pane.HTML(
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            disable_math=disable_math,
            enable_streaming=enable_streaming,
            height=height,
            height_policy=height_policy,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sanitize_hook=sanitize_hook,
            sanitize_html=sanitize_html,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def holo_views(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        backend: "bokeh | matplotlib | plotly" = None,
        center: bool = False,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        default_widgets: 'dict[str, Any]' = None,
        design: Any = None,
        format: "png | svg" = 'png',
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        linked_axes: bool = True,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        renderer: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        theme: 'Theme | str' = None,
        visible: bool = True,
        widget_layout: 'panel.layout.base.WidgetBox | panel.layout.base.Row | panel.layout.base.Column' = None,
        widget_location: "left | bottom | right | top | top_left | top_right | bottom_left | bottom_right | left_top | left_bottom | right_top | right_bottom" = 'right_top',
        widget_type: "individual | scrubber" = 'individual',
        widgets: 'dict[str, Any]' = {},
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.HoloViews:
        return self._add(_pane.HoloViews(
            align=align,
            aspect_ratio=aspect_ratio,
            backend=backend,
            center=center,
            css_classes=css_classes,
            default_layout=default_layout,
            default_widgets=default_widgets,
            design=design,
            format=format,
            height=height,
            height_policy=height_policy,
            linked_axes=linked_axes,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            renderer=renderer,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            theme=theme,
            visible=visible,
            widget_layout=widget_layout,
            widget_location=widget_location,
            widget_type=widget_type,
            widgets=widgets,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def ico(self,
        align: 'str | tuple[str, str]' = 'start',
        alt_text: 'str | None' = None,
        aspect_ratio: 'Any | None' = None,
        caption: 'str | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        embed: bool = False,
        enable_streaming: bool = False,
        fixed_aspect: bool = True,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        link_url: 'str | None' = None,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        target: str = '_blank',
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.ICO:
        return self._add(_pane.ICO(
            align=align,
            alt_text=alt_text,
            aspect_ratio=aspect_ratio,
            caption=caption,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            embed=embed,
            enable_streaming=enable_streaming,
            fixed_aspect=fixed_aspect,
            height=height,
            height_policy=height_policy,
            link_url=link_url,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            target=target,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def image(self,
        align: 'str | tuple[str, str]' = 'start',
        alt_text: 'str | None' = None,
        aspect_ratio: 'Any | None' = None,
        caption: 'str | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        embed: bool = False,
        enable_streaming: bool = False,
        fixed_aspect: bool = True,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        link_url: 'str | None' = None,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        target: str = '_blank',
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.Image:
        return self._add(_pane.Image(
            align=align,
            alt_text=alt_text,
            aspect_ratio=aspect_ratio,
            caption=caption,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            embed=embed,
            enable_streaming=enable_streaming,
            fixed_aspect=fixed_aspect,
            height=height,
            height_policy=height_policy,
            link_url=link_url,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            target=target,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def jpg(self,
        align: 'str | tuple[str, str]' = 'start',
        alt_text: 'str | None' = None,
        aspect_ratio: 'Any | None' = None,
        caption: 'str | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        embed: bool = False,
        enable_streaming: bool = False,
        fixed_aspect: bool = True,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        link_url: 'str | None' = None,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        target: str = '_blank',
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.JPG:
        return self._add(_pane.JPG(
            align=align,
            alt_text=alt_text,
            aspect_ratio=aspect_ratio,
            caption=caption,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            embed=embed,
            enable_streaming=enable_streaming,
            fixed_aspect=fixed_aspect,
            height=height,
            height_policy=height_policy,
            link_url=link_url,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            target=target,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def json(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        depth: int = 1,
        design: Any = None,
        enable_streaming: bool = False,
        encoder: JSONEncoder = None,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        hover_preview: bool = False,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        theme: "light | dark" = 'light',
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.JSON:
        return self._add(_pane.JSON(
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            default_layout=default_layout,
            depth=depth,
            design=design,
            enable_streaming=enable_streaming,
            encoder=encoder,
            height=height,
            height_policy=height_policy,
            hover_preview=hover_preview,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            theme=theme,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def la_te_x(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        renderer: "katex | mathjax" = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.LaTeX:
        return self._add(_pane.LaTeX(
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            height=height,
            height_policy=height_policy,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            renderer=renderer,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def markdown(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        dedent: bool = True,
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        disable_anchors: bool = False,
        disable_math: bool = False,
        enable_streaming: bool = False,
        extensions: 'list[Any]' = ['extra', 'smarty', 'codehilite'],
        hard_line_break: bool = False,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        plugins: 'list[Any]' = [],
        renderer: "'markdown-it' | myst | markdown" = 'markdown-it',
        renderer_options: 'dict[str, Any]' = {},
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.Markdown:
        return self._add(_pane.Markdown(
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            dedent=dedent,
            default_layout=default_layout,
            design=design,
            disable_anchors=disable_anchors,
            disable_math=disable_math,
            enable_streaming=enable_streaming,
            extensions=extensions,
            hard_line_break=hard_line_break,
            height=height,
            height_policy=height_policy,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            plugins=plugins,
            renderer=renderer,
            renderer_options=renderer_options,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def matplotlib(self,
        align: 'str | tuple[str, str]' = 'start',
        alt_text: 'str | None' = None,
        aspect_ratio: 'Any | None' = None,
        caption: 'str | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        dpi: int = 144,
        embed: bool = False,
        enable_streaming: bool = False,
        encode: bool = False,
        fixed_aspect: bool = True,
        format: "png | svg" = 'png',
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        high_dpi: bool = True,
        interactive: bool = False,
        link_url: 'str | None' = None,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        target: str = '_blank',
        tight: bool = False,
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.Matplotlib:
        return self._add(_pane.Matplotlib(
            align=align,
            alt_text=alt_text,
            aspect_ratio=aspect_ratio,
            caption=caption,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            dpi=dpi,
            embed=embed,
            enable_streaming=enable_streaming,
            encode=encode,
            fixed_aspect=fixed_aspect,
            format=format,
            height=height,
            height_policy=height_policy,
            high_dpi=high_dpi,
            interactive=interactive,
            link_url=link_url,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            target=target,
            tight=tight,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def pdf(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        embed: bool = False,
        enable_streaming: bool = False,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        start_page: int = 1,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.PDF:
        return self._add(_pane.PDF(
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            embed=embed,
            enable_streaming=enable_streaming,
            height=height,
            height_policy=height_policy,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            start_page=start_page,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def png(self,
        align: 'str | tuple[str, str]' = 'start',
        alt_text: 'str | None' = None,
        aspect_ratio: 'Any | None' = None,
        caption: 'str | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        embed: bool = False,
        enable_streaming: bool = False,
        fixed_aspect: bool = True,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        link_url: 'str | None' = None,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        target: str = '_blank',
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.PNG:
        return self._add(_pane.PNG(
            align=align,
            alt_text=alt_text,
            aspect_ratio=aspect_ratio,
            caption=caption,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            embed=embed,
            enable_streaming=enable_streaming,
            fixed_aspect=fixed_aspect,
            height=height,
            height_policy=height_policy,
            link_url=link_url,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            target=target,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def placeholder(self,
        _pane: Viewable = None,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        inplace: bool = False,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.Placeholder:
        return self._add(_pane.Placeholder(
            _pane=_pane,
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            height=height,
            height_policy=height_policy,
            inplace=inplace,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def plotly(self,
        _render_count: int = 0,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        click_data: 'dict[str, Any] | None' = None,
        clickannotation_data: 'dict[str, Any] | None' = None,
        config: 'dict[str, Any] | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        doubleclick_data: 'dict[str, Any] | None' = None,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        hover_data: 'dict[str, Any] | None' = None,
        link_figure: bool = True,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        relayout_data: 'dict[str, Any] | None' = None,
        restyle_data: 'list[Any]' = [],
        selected_data: 'dict[str, Any] | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        viewport: 'dict[str, Any] | None' = None,
        viewport_update_policy: "mouseup | continuous | throttle" = 'mouseup',
        viewport_update_throttle: int = 200,
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.Plotly:
        return self._add(_pane.Plotly(
            _render_count=_render_count,
            align=align,
            aspect_ratio=aspect_ratio,
            click_data=click_data,
            clickannotation_data=clickannotation_data,
            config=config,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            doubleclick_data=doubleclick_data,
            height=height,
            height_policy=height_policy,
            hover_data=hover_data,
            link_figure=link_figure,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            relayout_data=relayout_data,
            restyle_data=restyle_data,
            selected_data=selected_data,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            viewport=viewport,
            viewport_update_policy=viewport_update_policy,
            viewport_update_throttle=viewport_update_throttle,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def svg(self,
        align: 'str | tuple[str, str]' = 'start',
        alt_text: 'str | None' = None,
        aspect_ratio: 'Any | None' = None,
        caption: 'str | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        embed: bool = False,
        enable_streaming: bool = False,
        encode: bool = True,
        fixed_aspect: bool = True,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        link_url: 'str | None' = None,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        target: str = '_blank',
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.SVG:
        return self._add(_pane.SVG(
            align=align,
            alt_text=alt_text,
            aspect_ratio=aspect_ratio,
            caption=caption,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            embed=embed,
            enable_streaming=enable_streaming,
            encode=encode,
            fixed_aspect=fixed_aspect,
            height=height,
            height_policy=height_policy,
            link_url=link_url,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            target=target,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def str(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        enable_streaming: bool = False,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.Str:
        return self._add(_pane.Str(
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            enable_streaming=enable_streaming,
            height=height,
            height_policy=height_policy,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def vega(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        css_classes: 'list[Any]' = [],
        debounce: 'int | dict' = 20,
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        selection: Parameterized = None,
        show_actions: bool = False,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        theme: "excel | ggplot2 | quartz | vox | fivethirtyeight | dark | latimes | urbaninstitute | googlecharts" = None,
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.Vega:
        return self._add(_pane.Vega(
            align=align,
            aspect_ratio=aspect_ratio,
            css_classes=css_classes,
            debounce=debounce,
            default_layout=default_layout,
            design=design,
            height=height,
            height_policy=height_policy,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            selection=selection,
            show_actions=show_actions,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            theme=theme,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def video(self,
        align: 'str | tuple[str, str]' = 'start',
        aspect_ratio: 'Any | None' = None,
        autoplay: bool = False,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        loading: bool = False,
        loop: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        muted: bool = False,
        object: 'str | Path | BytesIO' = '',
        paused: bool = True,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        throttle: int = 250,
        time: float = 0,
        visible: bool = True,
        volume: int = 100,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.Video:
        return self._add(_pane.Video(
            align=align,
            aspect_ratio=aspect_ratio,
            autoplay=autoplay,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            height=height,
            height_policy=height_policy,
            loading=loading,
            loop=loop,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            muted=muted,
            object=object,
            paused=paused,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            throttle=throttle,
            time=time,
            visible=visible,
            volume=volume,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

    def web_p(self,
        align: 'str | tuple[str, str]' = 'start',
        alt_text: 'str | None' = None,
        aspect_ratio: 'Any | None' = None,
        caption: 'str | None' = None,
        css_classes: 'list[Any]' = [],
        default_layout: 'ListLike | NamedListLike' = None,
        design: Any = None,
        embed: bool = False,
        enable_streaming: bool = False,
        fixed_aspect: bool = True,
        height: 'int | None' = None,
        height_policy: "auto | fixed | fit | min | max" = 'auto',
        link_url: 'str | None' = None,
        loading: bool = False,
        margin: 'tuple[int, int] | int | str | None' = (5, 10),
        max_height: 'int | None' = None,
        max_width: 'int | None' = None,
        min_height: 'int | None' = None,
        min_width: 'int | None' = None,
        object: 'Any | None' = None,
        sizing_mode: "fixed | stretch_width | stretch_height | stretch_both | scale_width | scale_height | scale_both | None" = None,
        styles: 'dict[str, Any]' = {},
        stylesheets: 'list[Any]' = [],
        tags: 'list[Any]' = [],
        target: str = '_blank',
        visible: bool = True,
        width: 'int | None' = None,
        width_policy: "auto | fixed | fit | min | max" = 'auto',
        **kwargs: Any,
    ) -> _pane.WebP:
        return self._add(_pane.WebP(
            align=align,
            alt_text=alt_text,
            aspect_ratio=aspect_ratio,
            caption=caption,
            css_classes=css_classes,
            default_layout=default_layout,
            design=design,
            embed=embed,
            enable_streaming=enable_streaming,
            fixed_aspect=fixed_aspect,
            height=height,
            height_policy=height_policy,
            link_url=link_url,
            loading=loading,
            margin=margin,
            max_height=max_height,
            max_width=max_width,
            min_height=min_height,
            min_width=min_width,
            object=object,
            sizing_mode=sizing_mode,
            styles=styles,
            stylesheets=stylesheets,
            tags=tags,
            target=target,
            visible=visible,
            width=width,
            width_policy=width_policy,
            **kwargs,
        ))

