"""
This type stub file was generated by pyright.
"""

import os
import sys
from pathlib import Path
from types import ModuleType

__pre_all__ = ...
__version__ = ...
__version_info__ = ...
SKIP_MYPY_TEST = ...
def __getattr__(name: str) -> list[str]:
    ...

class ModuleDict(dict):
    def __missing__(self, key): # -> list[Any]:
        ...
    


class SubModule(ModuleType):
    ...


